# yaml-language-server: $schema=https://raw.githubusercontent.com/BGforgeNet/bgforge.yml/refs/heads/main/schema.json
translation:
  encoding: utf-8
  tra_dir: WeiDU-Weblate-GitHub/Languages
  skip_files:
    - "/polish/prompts.tra"
    - "/portuguese/prompts.tra"
    - "/russian/prompts.tra"
    - "/swedish/prompts.tra"

