# yaml-language-server: $schema=https://raw.githubusercontent.com/BGforgeNet/bgforge.yml/refs/heads/main/schema.json
translation:
  encoding: utf-8
  tra_dir: WeiDU-Weblate-GitHub/Languages
  skip_files:
    - WeiDU-Weblate-GitHub/Languagespolish/prompts.tra
    - WeiDU-Weblate-GitHub/portuguese/prompts.tra
    - WeiDU-Weblate-GitHub/russian/prompts.tra
    - WeiDU-Weblate-GitHub/swedish/prompts.tra

