# yaml-language-server: $schema=https://raw.githubusercontent.com/BGforgeNet/bgforge.yml/refs/heads/main/schema.json
translation:
  encoding: utf-8
  tra_dir: WeiDU-Weblate-GitHub/Languages
  skip_files:
    - "WeiDU-Weblate-GitHub/Languages/polish/prompts.tra"
    - "WeiDU-Weblate-GitHub/Languages/portuguese/prompts.tra"
    - "WeiDU-Weblate-GitHub/Languages/russian/prompts.tra"
    - "WeiDU-Weblate-GitHub/Languages/swedish/prompts.tra"

