# yaml-language-server: $schema=https://raw.githubusercontent.com/BGforgeNet/bgforge.yml/refs/heads/main/schema.json
translation:
  tra_dir: WeiDU-Weblate-GitHub/Languages
  encoding: utf-8
  all_utf8: true
  extract_fuzzy: true
  skip_files:
    - prompts.tra

