# yaml-language-server: $schema=https://raw.githubusercontent.com/BGforgeNet/bgforge.yml/refs/heads/main/schema.json
translation:
  encoding: utf-8
  all_utf8: true
  tra_dir: WeiDU-Weblate-GitHub/Languages
  skip_files:
    - prompts.tra

